name: Lint, Build, and Test PRs

on:
  pull_request:
    branches:
      - master # - build and test for PRs going into master.

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, build, and test
      run: |
        npm install -g @angular/cli
        npm ci
        ng lint
        ng build
        ng test
      env:
        CI: true
